/**
 * AUTH
 */
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';


/**
 * CHAT
 */

export const FECTH_MESSSAGE_SUCCESS = 'FECTH_MESSSAGE_SUCCESS';
export const FECTH_MESSSAGE_ERROR = 'FECTH_MESSSAGE_ERROR';


/**
 * Old CHAT LIST
 */

export const FECTH_OLD_CHAT_SUCCESS = 'FECTH_OLD_CHAT_SUCCESS';
export const FECTH_OLD_CHAT_ERROR = 'FECTH_OLD_CHAT_ERROR';


/**
 * RECENT CHAT 
 */

export const FETCH_OLD_ROOM_SUCCESS = 'FETCH_OLD_ROOM_SUCCESS';
export const FETCH_OLD_ROOM_ERROR = 'FETCH_OLD_ROOM_ERROR';
export const FECTH_OLD_MESSSAGE_SUCCESS = 'FECTH_OLD_MESSSAGE_SUCCESS';
export const FECTH_OLD_MESSSAGE_ERROR = 'FECTH_OLD_MESSSAGE_ERROR';


/**
 * ROOM
 */

export const FETCH_ROOM_SUCCESS = 'FETCH_ROOM_SUCCESS';
export const FETCH_ROOM_ERROR = 'FETCH_ROOM_ERROR';
export const REGISTER_ROOM = 'REGISTER_ROOM';

/**
 * CONTACT
 */

export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_ERROR = 'FETCH_CONTACT_ERROR';

/**
 * Gruops
 */

export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS';
export const FETCH_GROUP_ERROR = 'FETCH_GROUP_ERROR';
export const REGISTER_GROUP = 'REGISTER_GROUP';


/**
 * Group CHAT
 */

export const FECTH_GROUP_MESSSAGE_SUCCESS = 'FECTH_GROUP_MESSSAGE_SUCCESS';
export const FECTH_GROUP_MESSSAGE_ERROR = 'FECTH_GROUP_MESSSAGE_ERROR';


/**
 * Group CHAT rooms
 */

export const FETCH_GROUP_ROOM_SUCCESS = 'FETCH_GROUP_ROOM_SUCCESS';
export const FETCH_GROUP_ROOM_ERROR = 'FETCH_GROUP_ROOM_ERROR';
export const REGISTER_ROOM_GROUP = 'REGISTER_ROOM_GROUP';